site_name: SeqLike
# TODO: Add in the actual GitHub pages URL when it's ready.
# site_url: modernatx.github.io/seqlike

docs_dir: docs/

theme:
  name: "material"
  palette:
    primary: "indigo"
    accent: "indigo"
  icon:
    logo: "fontawesome/solid/book"
  features:
    - instant
    - tabs
  language: en

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: restructured-text

  # - mknotebooks:
  #     execute: true
  #     write_markdown: true
  #     allow_errors: false
  #     timeout: 1200
  #     binder: true
  #     binder_service_name: "gh"
  #     binder_branch: "master"
  #     binder_ui: "lab"

# Taken from here: https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
markdown_extensions:
#   - codehilite
  - admonition
#   - pymdownx.tabbed
#   - pymdownx.arithmatex
#   - pymdownx.details
#   - pymdownx.superfences
#   - markdown.extensions.attr_list

# extra_javascript:
#   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
#   - css/nb_mods.css
  - css/apidocs.css

# TODO: Uncomment and set values to correct ones as appropriate.
# repo_name: "modernatx/seqlike"
# repo_url: "https://github.com/modernatx/seqlike"
