name: Build documentation website

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    name: Build and deploy docs
    runs-on: ubuntu-latest

    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See: https://github.com/marketplace/actions/setup-miniconda
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge
          activate-environment: seqlike-dev
          environment-file: environment.yml
          use-mamba: true

      - name: Build docs
        run: |
          conda activate seqlike-dev
          python -m ipykernel install --user --name seqlike-dev
          python -m pip install -e .
          mkdocs build

      - name: Deploy docs to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-personal-access-token-personal_token
          personal_token: ${{ secrets.GHPAGES_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
          enable_jekyll: false
          disable_nojekyll: false
