name: SeqLike software tests

on: [pull_request]

jobs:
  build-environment:
    name: Build environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See: https://github.com/marketplace/actions/setup-conda
      - name: Setup anaconda
        uses: s-weigand/setup-conda@v1
        with:
          conda-channels: "conda-forge"

      # Build cache of environment
      - name: Cache conda environment
        id: cache-environment
        uses: actions/cache@v2
        # Conda environment build step depends on two files,
        # so we ensure that the hash key contains both their hashes.
        with:
          path: |
            seqlike-dev.tar.gz
          key: ${{ runner.os }}-env.${{ hashFiles('environment.yml') }}

      - name: Build environment
        if: steps.cache-environment.outputs.cache-hit != 'true'
        run: |
          conda env create -f environment.yml

      - name: Build environment
        uses: ./.github/actions/setup-env

      - name: Install conda-pack
        if: steps.cache-environment.outputs.cache-hit != 'true'
        run: conda install -c conda-forge conda-pack

      - name: Run conda-pack
        if: steps.cache-environment.outputs.cache-hit != 'true'
        run: conda pack -n seqlike-dev -o seqlike-dev.tar.gz

      # See: https://github.com/actions/upload-artifact
      - name: Upload environment
        uses: actions/upload-artifact@v2
        with:
          name: seqlike-dev-tarball
          path: seqlike-dev.tar.gz

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build-environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # https://github.com/actions/download-artifact
      - name: Download environment tarball
        uses: actions/download-artifact@v2
        with:
          name: seqlike-dev-tarball

      - name: Unpack environment and activate it
        run: bash scripts/ci/unpack_environment.sh

      - name: Run tests
        run: |
          source /tmp/seqlike-dev_env/bin/activate
          python -m pip install -e .
          pytest

      # # https://github.com/codecov/codecov-action
      # - name: Upload code coverage
      #   uses: codecov/codecov-action@v2
      #   with:
      #     fail_ci_if_error: true # optional (default = false)
      #     verbose: true # optional (default = false)

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    needs: build-environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # https://github.com/actions/download-artifact
      - name: Download environment tarball
        uses: actions/download-artifact@v2
        with:
          name: seqlike-dev-tarball

      - name: Unpack environment and activate it
        run: bash scripts/ci/unpack_environment.sh

      - name: Build docs
        run: |
          source /tmp/seqlike-dev_env/bin/activate
          python -m pip install -e .
          mkdocs build

      # - name: Netlify PR preview
      #   uses: netlify/actions/cli@master
      #   with:
      #     args: deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --dir=docs/_build/html/
